version: '3.2'
services:
  node_app: 
    container_name: node_app
    build: .
    ports:
      - "3333:3333"  
    depends_on:
      - 'rabbitmq'
      - mongo
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - rabbitmq_net
  mongo: 
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes: 
      - mongo:/var/lib/mongo/data
    networks:
      - rabbitmq_net
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: 'rabbitmq'
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_net

volumes:
  mongo:

networks:
  rabbitmq_net:
    driver: bridge

